version: "3.7"

services:
  app_proxy:
    environment:
      # Format : <id-app>_<nom-du-service>_1
      APP_HOST: youbs-watcharr_server_1
      APP_PORT: 3080

  server:
    image: ghcr.io/sbondco/watcharr:v4.2.1
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data:/data
